{!! Html::style('bootstrap/css/bootstrap.min.css') !!}
{!! Html::style('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css') !!}
{!! Html::style('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css') !!}
{!! Html::style('dist/css/AdminLTE.min.css') !!}
{!! Html::style('dist/css/skins/_all-skins.min.css') !!}
{!! Html::style('plugins/iCheck/flat/blue.css') !!}
{!! Html::style('plugins/morris/morris.css') !!}
{!! Html::style('plugins/jvectormap/jquery-jvectormap-1.2.2.css') !!}
{!! Html::style('plugins/datepicker/datepicker3.css') !!}
{!! Html::style('plugins/daterangepicker/daterangepicker-bs3.css') !!}
{!! Html::style('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') !!}
