{!! Html::script('frontend/jquery-1.11.3.min.js') !!}
{!! Html::script('frontend/js/bootstrap.min.js') !!}
{!! Html::script('frontend/js/jquery.cookie.js') !!}
{!! Html::script('frontend/js/waypoints.min.js') !!}
{!! Html::script('frontend/js/modernizr.js') !!}
{!! Html::script('frontend/js/bootstrap-hover-dropdown.js') !!}
{!! Html::script('frontend/js/owl.carousel.min.js') !!}
{!! Html::script('frontend/js/front.js') !!}
{!! Html::script('frontend/js/respond.min.js') !!}
